{
 "title": "Requests",
 "tags": [ "app" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(rest_api_go_request_duration_seconds_count,method)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(rest_api_go_request_duration_seconds_count,location)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(rest_api_go_request_duration_seconds_count,status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Performance and Responsiveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by(le) (\r\n    rate(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "95 Percentile"
    },
    {
     "expr": "histogram_quantile(\r\n  0.9,\r\n  sum by(le) (\r\n    rate(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "90 Percentile"
    },
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by(le) (\r\n    rate(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "50 Percentile"
    }
   ]
  },
  {
   "title": "Total Requests, 12h",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[12h])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])) by (method, location) > 0",
     "legendFormat": "{{method}} {{location}}"
    }
   ]
  },
  {
   "title": "Requests, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])) by (method, location) / scalar(sum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval]))) > 0\r\n",
     "legendFormat": "{{method}} {{location}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(label_replace(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group) / scalar(sum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])))> 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Response Time, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])) by (le) / scalar(sum(rate(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_received_bytes_total{method=~\"$method\", location=~\"$location\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Distribution of requests execution over time intervals",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.001\"}[$__interval])) > 0",
     "legendFormat": "0.001 sec"
    },
    {
     "expr": "(\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.005\"}[$__interval])) -\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.001\"}[$__interval]))\r\n) > 0",
     "legendFormat": "0.005 sec"
    },
    {
     "expr": "(\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.025\"}[$__interval])) -\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.005\"}[$__interval]))\r\n) > 0",
     "legendFormat": "0.025 sec"
    },
    {
     "expr": "(\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.2\"}[$__interval])) -\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.025\"}[$__interval]))\r\n) > 0",
     "legendFormat": "0.2 sec"
    },
    {
     "expr": "(\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"1\"}[$__interval])) -\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"0.2\"}[$__interval]))\r\n) > 0",
     "legendFormat": "1 sec"
    },
    {
     "expr": "(\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"4\"}[$__interval])) -\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"1\"}[$__interval]))\r\n) > 0",
     "legendFormat": "4 sec"
    },
    {
     "expr": "(\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"8\"}[$__interval])) -\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"4\"}[$__interval]))\r\n) > 0",
     "legendFormat": "8 sec"
    },
    {
     "expr": "(\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"+Inf\"}[$__interval])) -\r\n  sum(increase(rest_api_go_request_duration_seconds_bucket{method=~\"$method\", location=~\"$location\", status=~\"$status\", le=\"8\"}[$__interval]))\r\n) > 0",
     "legendFormat": "more 8 sec"
    }
   ]
  },
  {
   "title": "Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_response_sent_bytes_total{method=~\"$method\", location=~\"$location\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_duration_seconds_sum{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])) by (method, location) /\r\nsum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])) by (method, location) > 0",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_api_go_request_received_bytes_total{method=~\"$method\", location=~\"$location\"}[$__rate_interval])) by (method, location) /\r\nsum(rate(rest_api_go_request_duration_seconds_count{method=~\"$method\", location=~\"$location\", status=~\"$status\"}[$__rate_interval])) by (method, location) > 0",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}