Container(app_controller, "Контроллеры приложения", "Go, реализация mrserver.HttpController", "Обработчики HTTP-запросов: разбирают запрос, вызывают бизнес-логику, отправляют ответ или возвращают ошибку")
