// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-sysmess/mrtrace (interfaces: ContextManager)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockContextManager is a mock of ContextManager interface.
type MockContextManager struct {
	ctrl     *gomock.Controller
	recorder *MockContextManagerMockRecorder
}

// MockContextManagerMockRecorder is the mock recorder for MockContextManager.
type MockContextManagerMockRecorder struct {
	mock *MockContextManager
}

// NewMockContextManager creates a new mock instance.
func NewMockContextManager(ctrl *gomock.Controller) *MockContextManager {
	mock := &MockContextManager{ctrl: ctrl}
	mock.recorder = &MockContextManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextManager) EXPECT() *MockContextManagerMockRecorder {
	return m.recorder
}

// ExtractCorrelationID mocks base method.
func (m *MockContextManager) ExtractCorrelationID(arg0 context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractCorrelationID", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractCorrelationID indicates an expected call of ExtractCorrelationID.
func (mr *MockContextManagerMockRecorder) ExtractCorrelationID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractCorrelationID", reflect.TypeOf((*MockContextManager)(nil).ExtractCorrelationID), arg0)
}

// ExtractKeysValues mocks base method.
func (m *MockContextManager) ExtractKeysValues(arg0 context.Context) []interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractKeysValues", arg0)
	ret0, _ := ret[0].([]interface{})
	return ret0
}

// ExtractKeysValues indicates an expected call of ExtractKeysValues.
func (mr *MockContextManagerMockRecorder) ExtractKeysValues(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractKeysValues", reflect.TypeOf((*MockContextManager)(nil).ExtractKeysValues), arg0)
}

// ProcessID mocks base method.
func (m *MockContextManager) ProcessID(arg0 context.Context, arg1 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessID", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// ProcessID indicates an expected call of ProcessID.
func (mr *MockContextManagerMockRecorder) ProcessID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessID", reflect.TypeOf((*MockContextManager)(nil).ProcessID), arg0, arg1)
}

// WithGeneratedProcessID mocks base method.
func (m *MockContextManager) WithGeneratedProcessID(arg0 context.Context, arg1 string) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithGeneratedProcessID", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithGeneratedProcessID indicates an expected call of WithGeneratedProcessID.
func (mr *MockContextManagerMockRecorder) WithGeneratedProcessID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithGeneratedProcessID", reflect.TypeOf((*MockContextManager)(nil).WithGeneratedProcessID), arg0, arg1)
}

// WithProcessID mocks base method.
func (m *MockContextManager) WithProcessID(arg0 context.Context, arg1, arg2 string) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithProcessID", arg0, arg1, arg2)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// WithProcessID indicates an expected call of WithProcessID.
func (mr *MockContextManagerMockRecorder) WithProcessID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithProcessID", reflect.TypeOf((*MockContextManager)(nil).WithProcessID), arg0, arg1, arg2)
}
