// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-webcore/mrworker (interfaces: Task)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Caption mocks base method.
func (m *MockTask) Caption() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Caption")
	ret0, _ := ret[0].(string)
	return ret0
}

// Caption indicates an expected call of Caption.
func (mr *MockTaskMockRecorder) Caption() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Caption", reflect.TypeOf((*MockTask)(nil).Caption))
}

// Do mocks base method.
func (m *MockTask) Do(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTaskMockRecorder) Do(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTask)(nil).Do), arg0)
}

// Period mocks base method.
func (m *MockTask) Period() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Period")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Period indicates an expected call of Period.
func (mr *MockTaskMockRecorder) Period() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Period", reflect.TypeOf((*MockTask)(nil).Period))
}

// SignalDo mocks base method.
func (m *MockTask) SignalDo() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalDo")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// SignalDo indicates an expected call of SignalDo.
func (mr *MockTaskMockRecorder) SignalDo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalDo", reflect.TypeOf((*MockTask)(nil).SignalDo))
}

// Startup mocks base method.
func (m *MockTask) Startup() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Startup")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Startup indicates an expected call of Startup.
func (mr *MockTaskMockRecorder) Startup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Startup", reflect.TypeOf((*MockTask)(nil).Startup))
}

// Timeout mocks base method.
func (m *MockTask) Timeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Timeout indicates an expected call of Timeout.
func (mr *MockTaskMockRecorder) Timeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeout", reflect.TypeOf((*MockTask)(nil).Timeout))
}
